[project]
name = "secret-broadcast"
version = "0.0.1"
requires-python = ">=3.14"
dependencies = [
    "cryptography==46.0.3",
    "opencv-python==4.13.0.90",
    "python-dotenv==1.2.1",
    "requests==2.32.5",
]
